Create new objects with id set when saving.
spring-projects/spring-data-neo4j pull request #2173
Opened 2021-03-11 09:23 UTC by meistermeier

2021-03-11 12:37 UTC, michael-simons requested changes
In general I am wondering if there's a way to check upfront wether the recreation of the collections is actually necessary (at least if I don't understand the changes wrong, the templates seem to create at least the new approximate collection in all cases, regardless of whether working with immutable or not.).

2021-03-11 12:37 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/core/ReactiveNeo4jTemplate.java
> +													// if an internal id is used this must get set to link this entity in the next iteration
> get set

?

2021-03-11 12:37 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/core/ReactiveNeo4jTemplate.java
> +																	if (relationshipDescription.hasRelationshipProperties()) {
Interesting choice for a variable name.

2021-03-11 12:37 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/core/ReactiveNeo4jTemplate.java
> +																		Object lalelu = relationshipProperty.isDynamicAssociation()
I would rather prefer to bite it and deduplicate this conditions, similar on what we did together with the checks for cyclic dependencies, regardless of the fact that one lives in the imperative world and the other in the reactive world.

2021-03-11 12:37 UTC, michael-simons commented on src/test/java/org/springframework/data/neo4j/integration/imperative/RepositoryIT.java
> -		void saveWithGeneratedIdsReturnsObjectWithIdSet(
I appreciate that removal a lot.

2021-03-24 12:38 UTC, meistermeier commented
Merged with f9267d35a

2021-03-24 12:38 UTC, closed without merging