More relaxed inheritance mapping.
spring-projects/spring-data-neo4j pull request #2200
Opened 2021-03-26 08:31 UTC by meistermeier

With this PR it will be possible to map concrete classes coming from queries of abstract nodes without an annotation and as a consequence parent label.

2021-03-26 12:52 UTC, michael-simons requested changes
Only high level complains.

2021-03-26 12:52 UTC, michael-simons commented on src/test/java/org/springframework/data/neo4j/integration/imperative/InheritanceMappingIT.java
> +		assertThat(pets).hasSize(4);
Can we make sure those are different?

2021-03-26 12:52 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/core/mapping/Neo4jPersistentEntity.java
> +	 */
Unrelated but nice change :)

2021-03-26 12:52 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/core/mapping/Neo4jPersistentEntity.java
> +	boolean isExplicitEntity();
Can we please not add this? Instead do it internally the way it was before inside the mapping context?

2021-03-26 12:52 UTC, michael-simons commented on src/test/java/org/springframework/data/neo4j/integration/shared/common/AbstractNode.java
> +public abstract class AbstractNode {
`AbstractAnimal` or make cat and dogs ConcreteNode1 and 2.

2021-03-30 08:10 UTC, michael-simons approved these changes
Looks great now.

2021-03-30 08:57 UTC, closed without merging

2021-03-30 09:47 UTC, meistermeier commented
Merged with 01fa71994 (6.0.x) and c9fcb1433 (master)