issue/DATAGRAPH 1389
spring-projects/spring-data-neo4j pull request #537
Opened 2020-09-26 08:44 UTC by mp911de

- DATAGRAPH-1389 - Prepare issue branch.
- DATAGRAPH-1389 - Adopt to changes in Spring Data Commons.
- DATAGRAPH-1389 - Polishing.

2020-09-26 09:41 UTC, michael-simons requested changes
Comment and method say different.

2020-09-26 09:41 UTC, michael-simons commented on src/main/java/org/springframework/data/neo4j/repository/query/ReactiveNeo4jQueryMethod.java
> +	 * @return always false
🤔

2020-09-28 07:52 UTC, mp911de commented on src/main/java/org/springframework/data/neo4j/repository/query/ReactiveNeo4jQueryMethod.java
> +	 * @return always false
Done.

2020-09-28 10:17 UTC, michael-simons approved these changes

2020-09-28 12:00 UTC, michael-simons commented
Thanks a lot, Mark! Also for cutting the build time in half. Merged as 31826386212483f94d61d7c3621e676e2c4b89c1.

2020-09-28 12:00 UTC, closed without merging